/**
 * Jnoccio RPC token lifecycle.
 *
 * Manages the JNOCCIO_CORE_TOKEN used by the jnoccio-fusion /rpc endpoint
 * for bearer-token authentication.  The token lets OpenHuman desktop connect
 * in cloud mode.
 *
 * Token resolution (highest priority first):
 *   1. JNOCCIO_CORE_TOKEN environment variable (already set)
 *   2. ~/.env.jnoccio-rpc file (auto-generated on first boot)
 *
 * If neither exists, a 256-bit cryptographic token is generated, written to
 * ~/.env.jnoccio-rpc (mode 0600), and returned.
 */
import { randomBytes } from "crypto"
import fs from "fs"
import os from "os"
import path from "path"
import * as Log from "@jekko-ai/core/util/log"

const log = Log.create({ service: "jnoccio-token" })

const TOKEN_FILE = path.join(os.homedir(), ".env.jnoccio-rpc")
const ENV_VAR_NAME = "JNOCCIO_CORE_TOKEN"

/**
 * Returns the current RPC bearer token, generating and persisting one if
 * necessary.  Once resolved, the token is cached in `process.env` so that
 * the spawned jnoccio-fusion server inherits it.
 */
export function ensureJnoccioRpcToken(): string {
  // 1. Already in environment?
  const fromEnv = process.env[ENV_VAR_NAME]?.trim()
  if (fromEnv) {
    log.info("JNOCCIO_CORE_TOKEN loaded from environment")
    return fromEnv
  }

  // 2. Read from persistent file.
  const fromFile = readTokenFile()
  if (fromFile) {
    log.info("JNOCCIO_CORE_TOKEN loaded from ~/.env.jnoccio-rpc")
    process.env[ENV_VAR_NAME] = fromFile
    return fromFile
  }

  // 3. Generate, persist, and inject.
  const fresh = generateToken()
  writeTokenFile(fresh)
  process.env[ENV_VAR_NAME] = fresh
  log.info("JNOCCIO_CORE_TOKEN generated and saved to ~/.env.jnoccio-rpc")
  return fresh
}

/**
 * Returns the path to the token file for display purposes.
 */
export function tokenFilePath(): string {
  return TOKEN_FILE
}

/**
 * Reads the JNOCCIO_CORE_TOKEN value from ~/.env.jnoccio-rpc.
 * Returns undefined if the file doesn't exist or doesn't contain the key.
 */
function readTokenFile(): string | undefined {
  try {
    const content = fs.readFileSync(TOKEN_FILE, "utf8")
    for (const line of content.split("\n")) {
      const trimmed = line.trim()
      if (trimmed.startsWith("#") || !trimmed) continue
      const match = trimmed.match(/^JNOCCIO_CORE_TOKEN=(.+)$/)
      if (match) {
        const value = match[1].trim()
        if (value) return value
      }
    }
  } catch {
    // File doesn't exist or isn't readable.
  }
  return undefined
}

/**
 * Generates a 256-bit cryptographic token as a lowercase hex string.
 */
function generateToken(): string {
  return randomBytes(32).toString("hex")
}

/**
 * Writes the token to ~/.env.jnoccio-rpc with mode 0600.
 */
function writeTokenFile(token: string): void {
  try {
    const content = [
      "# Jnoccio-Fusion RPC bearer token for OpenHuman cloud-mode connections.",
      "# Auto-generated by Jekko. Do NOT commit this file.",
      `# Created: ${new Date().toISOString()}`,
      "# To view the token: cat ~/.env.jnoccio-rpc",
      `JNOCCIO_CORE_TOKEN=${token}`,
      "",
    ].join("\n")
    fs.writeFileSync(TOKEN_FILE, content, { mode: 0o600 })
  } catch (err) {
    log.error("failed to write ~/.env.jnoccio-rpc", {
      error: err instanceof Error ? err.message : String(err),
    })
  }
}
