//! Profile-aware compile flow: emit TOML / YAML / passthrough.

use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{anyhow, Context, Result};
use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::profile::{self, Profile};

pub enum Outcome {
    Wrote(PathBuf),
    Unchanged(PathBuf),
    Drift(PathBuf),
}

#[derive(Debug, Serialize)]
pub struct CompileReport {
    pub compiled: Vec<PathBuf>,
    pub unchanged: Vec<PathBuf>,
    pub drifted: Vec<PathBuf>,
}

pub fn compile_one(source: &Path, out_override: Option<&Path>, check: bool) -> Result<Outcome> {
    let info = profile::detect(source)?;
    let target = match out_override {
        Some(p) => p.to_path_buf(),
        None => default_target(source, &info.profile),
    };
    let (body, header) = emit(&info.profile, &info.raw)?;
    let source_name = source_reference(source);
    let banner = format!(
        "{h}Generated by: zyalc — DO NOT EDIT BY HAND.\n{h}Source: {src}\n{h}Regenerate: `cargo run -p zyalc -- compile {src}`\n{h}zyalc: sha256={hash} source={src}\n",
        h = header,
        src = source_name,
        hash = sha256(&info.raw),
    );
    let final_bytes = match info.profile {
        Profile::Runbook => body, // runbook passthrough — sentinels are strict
        _ => format!("{banner}{body}"),
    };
    if check {
        let existing = match fs::read_to_string(&target) {
        Ok(s) => s,
        Err(_) => String::new(),
    };
        if existing == final_bytes {
            return Ok(Outcome::Unchanged(target));
        }
        return Ok(Outcome::Drift(target));
    }
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("mkdir {}", parent.display()))?;
    }
    let existing = match fs::read_to_string(&target) {
        Ok(s) => s,
        Err(_) => String::new(),
    };
    if existing == final_bytes {
        return Ok(Outcome::Unchanged(target));
    }
    fs::write(&target, &final_bytes)
        .with_context(|| format!("write {}", target.display()))?;
    Ok(Outcome::Wrote(target))
}

pub fn compile_all(root: &Path, check: bool) -> Result<CompileReport> {
    let mut compiled = Vec::new();
    let mut unchanged = Vec::new();
    let mut drifted = Vec::new();
    for source in discover(root)? {
        match compile_one(&source, None, check)? {
            Outcome::Wrote(p) => compiled.push(p),
            Outcome::Unchanged(p) => unchanged.push(p),
            Outcome::Drift(p) => drifted.push(p),
        }
    }
    Ok(CompileReport {
        compiled,
        unchanged,
        drifted,
    })
}

#[derive(Debug)]
pub struct InspectInfo {
    pub profile: String,
    pub target: Option<PathBuf>,
    pub schema: Option<String>,
}

pub fn inspect(source: &Path) -> Result<InspectInfo> {
    let info = profile::detect(source)?;
    let target = Some(default_target(source, &info.profile));
    let schema = match &info.profile {
        Profile::DeclarativeToml { schema } | Profile::Workflow { schema } => Some(schema.clone()),
        Profile::Runbook => None,
    };
    Ok(InspectInfo {
        profile: info.profile.to_string(),
        target,
        schema,
    })
}

fn default_target(source: &Path, profile: &Profile) -> PathBuf {
    match profile {
        Profile::DeclarativeToml { .. } => {
            // Declarative `.zyal` sources canonically live under `agent/zyal/`
            // per the jankurai v1.0.0 conformance rule; the compiled TOML
            // belongs one directory up at `agent/<stem>.toml` so other tools
            // (proof-lanes, validators) find it on the well-known path.
            let stem = source.file_stem().and_then(|s| s.to_str()).unwrap_or("out");
            if let Some(parent) = source.parent().and_then(|p| p.parent()) {
                parent.join(format!("{stem}.toml"))
            } else {
                source.with_extension("toml")
            }
        }
        Profile::Workflow { .. } => {
            let stem = source.file_stem().and_then(|s| s.to_str()).unwrap_or("workflow");
            PathBuf::from(format!(".github/workflows/{stem}.yml"))
        }
        Profile::Runbook => source.with_extension("yml"),
    }
}

fn source_reference(source: &Path) -> String {
    source
        .strip_prefix(".")
        .unwrap_or(source)
        .display()
        .to_string()
}

/// Returns (body, comment-line-prefix). The comment prefix differs between
/// TOML (`# `) and YAML (`# `), so we centralise it here for the trailer.
fn emit(profile: &Profile, raw: &str) -> Result<(String, String)> {
    match profile {
        Profile::Runbook => Ok((raw.to_string(), String::new())),
        Profile::DeclarativeToml { .. } => Ok((emit_toml(raw)?, "# ".into())),
        Profile::Workflow { .. } => Ok((emit_workflow(raw)?, "# ".into())),
    }
}

fn emit_toml(raw: &str) -> Result<String> {
    let body = strip_pragmas(raw);
    let parsed: serde_yaml::Value = serde_yaml::from_str(&body)
        .context("parse declarative YAML body")?;
    let toml_value = yaml_to_toml(parsed)?;
    let rendered = toml::to_string_pretty(&toml_value)
        .context("render TOML")?;
    Ok(rendered)
}

fn emit_workflow(raw: &str) -> Result<String> {
    let body = strip_pragmas(raw);
    let parsed: serde_yaml::Value = serde_yaml::from_str(&body)
        .context("parse workflow YAML body")?;
    let rendered = serde_yaml::to_string(&parsed)
        .context("render workflow YAML")?;
    Ok(rendered)
}

fn strip_pragmas(raw: &str) -> String {
    raw.lines()
        .filter(|line| !line.trim_start().starts_with("# zyal:"))
        .filter(|line| !line.trim_start().starts_with("# zyalc:"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Convert a YAML mapping into a TOML value. The declarative schema uses
/// `lanes: [...]` at the top level; TOML's natural array-of-tables form is
/// `[[lane]]`, so we rename the key during translation.
fn yaml_to_toml(value: serde_yaml::Value) -> Result<toml::Value> {
    use serde_yaml::Value as Y;
    let map = match value {
        Y::Mapping(m) => m,
        _ => return Err(anyhow!("declarative body must be a YAML mapping")),
    };
    let mut tbl = toml::value::Table::new();
    for (k, v) in map {
        let key = match k.as_str() {
            Some(s) => s.to_string(),
            None => return Err(anyhow!("non-string key")),
        };
        if key == "lanes" {
            let array = match v.as_sequence() {
                Some(arr) => arr.clone(),
                None => return Err(anyhow!("lanes must be a sequence")),
            };
            let mut arr = Vec::with_capacity(array.len());
            for item in array {
                arr.push(yaml_value_to_toml(item)?);
            }
            tbl.insert("lane".into(), toml::Value::Array(arr));
        } else {
            tbl.insert(key, yaml_value_to_toml(v)?);
        }
    }
    Ok(toml::Value::Table(tbl))
}

fn yaml_value_to_toml(v: serde_yaml::Value) -> Result<toml::Value> {
    use serde_yaml::Value as Y;
    Ok(match v {
        Y::Null => toml::Value::String(String::new()),
        Y::Bool(b) => toml::Value::Boolean(b),
        Y::Number(n) => {
            if let Some(i) = n.as_i64() {
                toml::Value::Integer(i)
            } else if let Some(u) = n.as_u64() {
                toml::Value::Integer(u as i64)
            } else if let Some(f) = n.as_f64() {
                toml::Value::Float(f)
            } else {
                toml::Value::String(n.to_string())
            }
        }
        Y::String(s) => toml::Value::String(s),
        Y::Sequence(seq) => {
            let mut arr = Vec::with_capacity(seq.len());
            for item in seq {
                arr.push(yaml_value_to_toml(item)?);
            }
            toml::Value::Array(arr)
        }
        Y::Mapping(m) => {
            let mut tbl = toml::value::Table::new();
            for (k, v) in m {
                let key = match k.as_str() {
                    Some(s) => s.to_string(),
                    None => return Err(anyhow!("non-string key in mapping")),
                };
                tbl.insert(key, yaml_value_to_toml(v)?);
            }
            toml::Value::Table(tbl)
        }
        Y::Tagged(t) => yaml_value_to_toml(t.value)?,
    })
}

fn sha256(raw: &str) -> String {
    let mut h = Sha256::new();
    h.update(raw.as_bytes());
    format!("{:x}", h.finalize())
}

fn discover(root: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    let candidates = ["agent/zyal", "agent/workflows"];
    for c in candidates {
        let p = root.join(c);
        if p.is_file() && p.extension().and_then(|e| e.to_str()) == Some("zyal") {
            out.push(p);
        } else if p.is_dir() {
            for entry in fs::read_dir(&p)? {
                let entry = entry?;
                let path = entry.path();
                if path.extension().and_then(|e| e.to_str()) == Some("zyal") {
                    out.push(path);
                }
            }
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_strips_pragmas() {
        let raw = "# zyal: declarative target=toml schema=test@1\nschema_version: \"1.0.0\"\nlanes:\n  - name: a\n    command_id: x.a\n    cost: 1\n";
        let stripped = strip_pragmas(raw);
        assert!(!stripped.contains("# zyal:"));
        assert!(stripped.contains("schema_version"));
    }

    #[test]
    fn toml_emit_basic() {
        let raw = "# zyal: declarative target=toml schema=t@1\nschema_version: \"1.0.0\"\nlanes:\n  - name: a\n    cost: 1\n";
        let out = emit_toml(raw).expect("emit");
        assert!(out.contains("schema_version"));
        assert!(out.contains("[[lane]]"));
        assert!(out.contains("name = \"a\""));
    }

    #[test]
    fn idempotent_emit() {
        let raw = "# zyal: declarative target=toml schema=t@1\nschema_version: \"1.0.0\"\nlanes:\n  - name: a\n    cost: 1\n";
        let a = emit_toml(raw).unwrap();
        let b = emit_toml(raw).unwrap();
        assert_eq!(a, b, "compile must be idempotent");
    }

    #[test]
    fn source_reference_preserves_canonical_subdirectory() {
        assert_eq!(
            source_reference(Path::new("./agent/zyal/sandbox-lanes.zyal")),
            "agent/zyal/sandbox-lanes.zyal"
        );
    }
}
