import { Schema } from "effect"
import type { ZyalArm, ZyalScript } from "./schema-core"

export const ZyalPreview = Schema.Struct({
  id: Schema.String,
  contract_version: Schema.String,
  runtime_sentinel_version: Schema.String,
  research_block_version: Schema.String,
  armed: Schema.Boolean,
  objective: Schema.String,
  loop_policy: Schema.optional(Schema.String),
  stop_checks: Schema.Array(Schema.String),
  checkpoint_checks: Schema.Array(Schema.String),
  worker_count: Schema.Number,
  permissions: Schema.Array(Schema.String),
  risks: Schema.Array(Schema.String),
  incubator_enabled: Schema.Boolean,
  incubator_passes: Schema.Array(Schema.String),
  incubator_budget: Schema.optional(Schema.Record(Schema.String, Schema.Number)),
  promotion_threshold: Schema.optional(Schema.Number),
  routing_summary: Schema.optional(Schema.String),
  exclusion_summary: Schema.optional(Schema.String),
  cleanup_summary: Schema.optional(Schema.String),
  readiness_summary: Schema.optional(Schema.String),
  incubator_risks: Schema.Array(Schema.String),
  on_handler_count: Schema.Number,
  fan_out_enabled: Schema.Boolean,
  fan_out_summary: Schema.optional(Schema.String),
  guardrail_count: Schema.Number,
  guardrails_summary: Schema.optional(Schema.String),
  assertions_enabled: Schema.Boolean,
  retry_enabled: Schema.Boolean,
  hook_count: Schema.Number,
  hooks_summary: Schema.optional(Schema.String),
  constraint_count: Schema.Number,
  constraints_summary: Schema.optional(Schema.String),
  workflow_enabled: Schema.Boolean,
  workflow_summary: Schema.optional(Schema.String),
  memory_store_count: Schema.Number,
  memory_summary: Schema.optional(Schema.String),
  evidence_enabled: Schema.Boolean,
  evidence_summary: Schema.optional(Schema.String),
  approval_gate_count: Schema.Number,
  approvals_summary: Schema.optional(Schema.String),
  skills_count: Schema.Number,
  skills_summary: Schema.optional(Schema.String),
  sandbox_enabled: Schema.Boolean,
  sandbox_summary: Schema.optional(Schema.String),
  security_enabled: Schema.Boolean,
  security_summary: Schema.optional(Schema.String),
  observability_enabled: Schema.Boolean,
  observability_summary: Schema.optional(Schema.String),
  arming_enabled: Schema.Boolean,
  arming_summary: Schema.optional(Schema.String),
  capabilities_rule_count: Schema.Number,
  capabilities_summary: Schema.optional(Schema.String),
  quality_enabled: Schema.Boolean,
  quality_summary: Schema.optional(Schema.String),
  experiments_enabled: Schema.Boolean,
  experiments_summary: Schema.optional(Schema.String),
  models_enabled: Schema.Boolean,
  models_summary: Schema.optional(Schema.String),
  budgets_enabled: Schema.Boolean,
  budgets_summary: Schema.optional(Schema.String),
  triggers_count: Schema.Number,
  triggers_summary: Schema.optional(Schema.String),
  rollback_enabled: Schema.Boolean,
  rollback_summary: Schema.optional(Schema.String),
  done_enabled: Schema.Boolean,
  done_summary: Schema.optional(Schema.String),
  repo_intel_enabled: Schema.Boolean,
  repo_intel_summary: Schema.optional(Schema.String),
  fleet_enabled: Schema.Boolean,
  fleet_max_workers: Schema.Number,
  fleet_summary: Schema.optional(Schema.String),
  research_enabled: Schema.Boolean,
  research_mode: Schema.optional(Schema.String),
  research_max_parallel: Schema.Number,
  research_timeout_seconds: Schema.optional(Schema.Number),
  research_summary: Schema.optional(Schema.String),
  research_provider_summary: Schema.optional(Schema.String),
  research_extraction_summary: Schema.optional(Schema.String),
  research_evidence_summary: Schema.optional(Schema.String),
  research_safety_summary: Schema.optional(Schema.String),
  research_budget_summary: Schema.optional(Schema.String),
  taint_enabled: Schema.Boolean,
  taint_label_count: Schema.Number,
  taint_forbid_count: Schema.Number,
  taint_summary: Schema.optional(Schema.String),
  interop_enabled: Schema.Boolean,
  interop_summary: Schema.optional(Schema.String),
  runtime_enabled: Schema.Boolean,
  runtime_summary: Schema.optional(Schema.String),
  capability_negotiation_enabled: Schema.Boolean,
  capability_negotiation_summary: Schema.optional(Schema.String),
  memory_kernel_enabled: Schema.Boolean,
  memory_kernel_summary: Schema.optional(Schema.String),
  evidence_graph_enabled: Schema.Boolean,
  evidence_graph_summary: Schema.optional(Schema.String),
  trust_enabled: Schema.Boolean,
  trust_summary: Schema.optional(Schema.String),
  requirements_enabled: Schema.Boolean,
  requirements_summary: Schema.optional(Schema.String),
  evaluation_enabled: Schema.Boolean,
  evaluation_summary: Schema.optional(Schema.String),
  release_enabled: Schema.Boolean,
  release_summary: Schema.optional(Schema.String),
  roles_count: Schema.Number,
  roles_summary: Schema.optional(Schema.String),
  channels_count: Schema.Number,
  channels_summary: Schema.optional(Schema.String),
  imports_count: Schema.Number,
  imports_summary: Schema.optional(Schema.String),
  reasoning_privacy_enabled: Schema.Boolean,
  reasoning_privacy_summary: Schema.optional(Schema.String),
  unsupported_feature_policy_enabled: Schema.Boolean,
  unsupported_feature_policy_summary: Schema.optional(Schema.String),
})

export type ZyalPreview = Schema.Schema.Type<typeof ZyalPreview>

export type ZyalParsed = {
  readonly spec: ZyalScript
  readonly arm: ZyalArm | undefined
  readonly specHash: string
  readonly preview: ZyalPreview
}

export function assertZyalTopLevelKeys(input: Record<string, unknown>) {
  const allowed = new Set([
    "version",
    "intent",
    "confirm",
    "id",
    "job",
    "loop",
    "stop",
    "context",
    "checkpoint",
    "tasks",
    "incubator",
    "agents",
    "mcp",
    "permissions",
    "ui",
    "on",
    "fan_out",
    "guardrails",
    "assertions",
    "retry",
    "hooks",
    "constraints",
    "workflow",
    "memory",
    "evidence",
    "approvals",
    "skills",
    "sandbox",
    "security",
    "observability",
    "arming",
    "capabilities",
    "quality",
    "experiments",
    "models",
    "budgets",
    "triggers",
    "rollback",
    "done",
    "repo_intelligence",
    "fleet",
    "research",
    "taint",
    "interaction",
    "interop",
    "runtime",
    "capability_negotiation",
    "memory_kernel",
    "evidence_graph",
    "trust",
    "requirements",
    "evaluation",
    "release",
    "roles",
    "channels",
    "imports",
    "reasoning_privacy",
    "unsupported_feature_policy",
  ])
  for (const key of Object.keys(input)) {
    if (!allowed.has(key)) {
      throw new Error(`Unknown ZYAL top-level key: ${key}`)
    }
  }
}
